export const SUBMIT_REQUEST = 'SUBMIT_REQUEST';
export const SET_REQUEST = 'SET_REQUEST';

export const REQUEST_DELIVERY_START = 'REQUEST_DELIVERY_START';
export const REQUEST_DELIVERY_SUCCESS = 'REQUEST_DELIVERY_SUCCESS';
export const REQUEST_DELIVERY_FAIL = 'REQUEST_DELIVERY_FAIL';
export const REQUEST_INIT = 'REQUEST_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';